"""Add new user profile fields

Revision ID: b1ae50ced515
Revises: a509477a0738
Create Date: 2025-09-28 20:18:29.679861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ae50ced515'
down_revision = 'a509477a0738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('place_of_birth', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('marital_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('current_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('current_job', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('job_title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('company', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('company')
        batch_op.drop_column('job_title')
        batch_op.drop_column('current_job')
        batch_op.drop_column('current_city')
        batch_op.drop_column('marital_status')
        batch_op.drop_column('place_of_birth')
        batch_op.drop_column('date_of_birth')

    # ### end Alembic commands ###
